# 窗口
window:
  width: 600
  height: 420

# 球
ball:
  width: 25
  height: 25
  positionX: 175
  positionY: 200

# 块
block:
  width: 75
  height: 75

# 挡板
paddle:
  width: 125
  height: 25
  positionX: 125
  positionY: 25